/* Get cart */

export const GET_CART_REQUEST = 'Request/GET_CART';
export const GET_CART_RECEIVE = 'Receive/GET_CART';
export const GET_CART_ERROR = 'GET_CART_ERROR';

/* Add product to cart */

export const UPDATE_PRODUCT_IN_CART_REQUEST = 'Request/UPDATE_PRODUCT_IN_CART';
export const UPDATE_PRODUCT_IN_CART_RECEIVE = 'Receive/UPDATE_PRODUCT_IN_CART';
export const UPDATE_PRODUCT_IN_CART_ERROR = 'UPDATE_PRODUCT_IN_CART_ERROR';

/* Delete product from cart */

export const DELETE_PRODUCT_FROM_CART_REQUEST = 'Request/DELETE_PRODUCT_FROM_CART';
export const DELETE_PRODUCT_FROM_CART_RECEIVE = 'Receive/DELETE_PRODUCT_FROM_CART';
export const DELETE_PRODUCT_FROM_CART_ERROR = 'DELETE_PRODUCT_FROM_CART_ERROR';

/* Checkout cart */

export const CHECKOUT_CART_REQUEST = 'Request/CHECKOUT_CART';
export const CHECKOUT_CART_RECEIVE = 'Receive/CHECKOUT_CART';
export const CHECKOUT_CART_ERROR = 'CHECKOUT_CART_ERROR';
