/* Get products */

export const GET_PRODUCTS_REQUEST = 'Request/GET_PRODUCTS';
export const GET_PRODUCTS_RECEIVE = 'Receive/GET_PRODUCTS';
export const GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR';

/* Other */

export const RESTORE_DEFAULT_PRODUCTS_REDUCER = 'RESTORE_DEFAULT_PRODUCTS_REDUCER';
