export const SET_NEW_CATEGORY_NAMES = 'Search/SET_NEW_CATEGORY_NAMES';
export const SET_NEW_SEARCH_TEXT = 'Search/SET_NEW_SEARCH_TEXT';
export const SET_NEW_SUPPLIER_ID = 'Search/SET_NEW_SUPPLIER_ID';
export const SET_NEW_PAGINATION = 'Search/SET_NEW_PAGINATION';
export const SET_NEW_SORT_RULE = 'Search/SET_NEW_SORT_RULE';
export const SET_NEW_SORT_ORDER = 'Search/SET_NEW_SORT_ORDER';

/* Other */
export const INIT_DEFAULT_SEARCH_REDUCER = 'INIT_DEFAULT_SEARCH_REDUCER';
export const RESTORE_DEFAULT_SEARCH_REDUCER = 'RESTORE_DEFAULT_SEARCH_REDUCER';
